config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :quizzes, only: [:show] do
    resources :questions, only: [] do
      resources :user_answers, only: [:create]
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quiz
end

app/models/quiz.rb
class Quiz < ApplicationRecord
end

app/models/user_answer.rb
class UserAnswer < ApplicationRecord
  belongs_to :user
  belongs_to :question
  belongs_to :answer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
    def show
        @quiz = Quiz.find(params[:id])
        @questions = @quiz.questions.includes(:answers)
    end
end

app/controllers/user_answers_controller.rb
class UserAnswersController < ApplicationController
    def create
        UserAnswer.create(user_answer_params)
        redirect_to next_question_path
    end

    private
        def user_answer_params
            params.require(:user_answer).permit(:user_id, :question_id, :answer_id)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/user_answers_helper.rb
module UserAnswersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ass3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quizzes/show.html.erb
<% @questions.each do |question| %>
 <p><%= question.content %></p>
 <%= form_with(url: user_answers_path, method: :post) do |form| %>
 <% question.answers.each do |answer| %>
 <%= form.radio_button :answer_id, answer.id %>
 <%= answer.content %><br>
 <% end %>
 <%= form.submit "Submit" %>
 <% end %>
<% end %>